apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kubeflow-tls
  namespace: istio-system
spec:
  secretName: kubeflow-tls
  dnsNames:
    - "kubeflow.local"  # 내부 로컬용
  issuerRef:
    name: kubeflow-selfsigned
    kind: ClusterIssuer
  privateKey:
    rotationPolicy: Always